name: tonic
description: >
  Classes and methods for representing and manipulating concepts from music theory:
  Pitch, PitchClass, Interval, Scale, Chord.
version: 0.2.1
authors:
- Oliver Steele <steele@osteele.com>
- Rody Davis <rody.davis.jr@gmail.com>
homepage: http://github.com/osteele/dart-tonic
documentation:

environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'

dev_dependencies:
  test: ^1.0.0
