name: tonic
description: >
  Classes and methods for representing and manipulating concepts from music theory:
  Pitch, PitchClass, Interval, Scale, Chord.
version: 0.0.2
authors:
- Oliver Steele <steele@osteele.com>
- Rody Davis <rody.davis.jr@gmail.com>
homepage: http://github.com/osteele/dart-tonic

dev_dependencies:
  test: ^1.0.0
